title: IRIII.2
subtitle: "Quantitative Methods in the Study of International Relations"
email: steven.miller@ekohist.su.se
dept: ""
univ: ""
job: Ph.D. Student
address: "Institutionen för ekonomisk historia och internationella relationer<br />106 91 Stockholm"

baseurl: ""
url: "http://ir3-2.svmiller.com/"


markdown: kramdown
permalink: blog/:year/:month/:title
